package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Activator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/workspace/zulu-platform-build@2/zulu-src.git/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, January 19, 2023 8:45:17 AM PST
*/

public interface Activator extends ActivatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Activator
